### ISSUE TITLE
fix text grey prop in service card

### ISSUE THREAD

**Issue by Ozoemenamsolomon** [Ozoemenamsolomon/orthoex-store#7]
|![orthoex ng_composites(Pixel 5)](https://user-images.githubusercontent.com/52500221/207532784-5d1c97b8-b8cc-468b-b0d0-b3a475ecf375.png)|
|--|
|the default colour of the description shouldn't be grey|
@ebuka-nwabueze I guess you made the changes in this PR #4

**Comment by ebuka-nwabueze** [comment]
Fixed

**Comment by ebuka-nwabueze** [comment]
I will make the change the current branch i'm working on
